name: ci

on:
  push:
    branches: [master]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          # 选择要使用的 node 版本
          node-version: '20'

      # 缓存 pnpm 缓存和 node_modules
      - name: Cache dependencies
        uses: actions/cache@v4.0.2
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      # 运行构建脚本
      - name: Build frontend
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为Vite项目的默认输出目录
          build_dir: ./dist
          fqdn: "wh.srap.link"
        env:
          GITHUB_TOKEN: ${{ secrets.GAYHUB_TOKEN }}
